name: Apply Formatting

on:
  workflow_call:
    inputs:
      php:
        type: string
        default: '8.2'

permissions:
  contents: write

jobs:
  laravel:
    uses: laravel/.github/.github/workflows/coding-standards.yml@main
    with:
      php: ${{ inputs.php }}